# Generated by Django 4.0.5 on 2022-10-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_user_websiteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='websiteuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='websiteuser',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='websiteuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='websiteuser',
            name='username',
        ),
    ]
